project:
  type: site

execute:
  freeze: true

site:
  title: "Quarto Docs"
  page-navigation: true
  site-url: https://pommevilla.github.io/quarto-web-redesign
  repo-url: https://github.com/pommevilla/quarto-web-redesign
  repo-actions: [edit, issue]


  navbar:
    search: true
    logo: docs/images/quarto-logo.png
    background: "light"
    right:
      - text: "About"
        url: docs/about/overview.qmd
      - text: "Get Started"
        url: docs/getting_started/overview.qmd
      - text: "Guides"
        url: docs/how_to/overview.qmd
      - text: "Reference"
        url: docs/references/overview.qmd
      - text: "Gallery"
        url: docs/gallery/overview.qmd

  sidebar:
    style: "docked"
    collapse-level: 1
    align: left
    contents:
      - section: "Getting Started"
        contents:
          - docs/getting_started/overview.qmd
          - docs/getting_started/installation.qmd
          - docs/getting_started/first_quarto.qmd
      - section: "Guides"
        contents:
          - docs/how_to/overview.qmd
      - section: "Reference"
        contents:
          - docs/references/overview.qmd


format:
  html:
    theme: cosmo
    code-background: true
    code-copy: true
    css: styles/styles.css
    toc: true
