project:
  type: site

execute:
  freeze: true

site:
  title: "Quarto Docs"
  page-navigation: true
  site-url: https://pommevilla.github.io/quarto-web-redesign
  repo-url: https://github.com/pommevilla/quarto-web-redesign
  repo-actions: [edit, issue]


  navbar:
    type: light
    search: true
    logo: docs/images/quarto-logo.png
    background: "light"
    right:
      - text: "Tutorials"
        menu:
          - text: "Getting started" 
            file: docs/tutorials/getting_started/overview.qmd
          - text: "Quarto Projects" 
            file: docs/tutorials/quarto_projects/overview.qmd
      - text: "Guides"
        url: docs/guides/overview.qmd
      - text: "References"
        url: docs/references/overview.qmd
      - text: "Gallery"
        url: docs/gallery/overview.qmd
      - text: "About"
        url: docs/about/overview.qmd

  sidebar:
    style: "docked"
    collapse-level: 1
    align: left
    contents:
      - section: "Tutorials"
        contents:
          - section: "Getting Started"
            contents: 
            - docs/tutorials/getting_started/overview.qmd
            - docs/tutorials/getting_started/installation.qmd
            - docs/tutorials/getting_started/first_quarto.qmd
            - docs/tutorials/getting_started/different_outputs.qmd
          - section: "Quarto Projects"
            contents:
              - docs/projects/overview.qmd
      - section: "Guides"
        contents:
          - docs/guides/overview.qmd
      - section: "Reference"
        contents:
          - docs/references/overview.qmd


format:
  html:
    theme:
      - cosmo
      - styles/custom.scss
    code-background: true
    code-copy: true
    # css: styles/custom.scss
    toc: true
